// react/src/components/Login.tsx
import React, { Component } from 'react';

export const Login = () => {
  return (
    <div className="popup popup--open">
      <div className="popup__header">
        <div title="Close" className="close layout--center">
          X
        </div>
      </div>
      <div className="popup__body layout--center">
        <div className="popup__body-inner">
          <div className="form">
            <div className="form__title">
              JOIN <span className="highlight">#</span>DEVRANT
            </div>
            <div className="form__description">
              Vote and comment on others' rants. Post your own.
            </div>
            <form name="login">
              <div className="login">
                <input type="text" placeholder="USERNAME" />
                <input type="password" placeholder="PASSWORD" />

                <div className="loader">
                  <div className="spinner" />
                </div>

                <div className="form__error">Some fields are missing !</div>

                <input type="submit" value="LET ME IN" />
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
};

// angular/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {
  constructor(private router: Router) {
  }


  ngOnInit() {
  }

  closeLoginModel() {
    this.router.navigateByUrl('');
    // this.isShowLoginModel = false;
  }
}

<div class="popup popup--open">
    <div class="popup__header">
        <div title="Close" class="close layout--center" (click)="closeLoginModel()">
            X
        </div>
    </div>
    <div class="popup__body layout--center">
        <div class="popup__body-inner">

            <div class="form">
                <div class="form__title">
                    JOIN <span class="highlight">#</span>DEVRANT
                </div>
                <div class="form__description">
                    Vote and comment on others' rants. Post your own.
                </div>
                <form name="login">
                    <div class="login">

                        <input type="text" placeholder="USERNAME" />
                        <input type="password" placeholder="PASSWORD" />

                        <div class="loader">
                            <div class="spinner"></div>
                        </div>

                        <div class="form__error">
                            Some fields are missing !
                        </div>

                        <input type="submit" value="LET ME IN" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
