// angular/src/app/header/header.component.ts
import { Component, OnInit, Input, Output } from '@angular/core';
import { Router } from '@angular/router';
import { AppComponent } from 'app/app.component';

@Component({
  selector: 'header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {

  constructor(private router: Router) { }
  ngOnInit() {
  }

  popUp: any[];

  login() {
    this.router.navigateByUrl('login');
  }

  logout() {
  }
}

<div class="page">

  <!-- Start of Header -->
  <!-- ======================= -->

  <section class="header layout--center">
    <div class="header__content layout--wrapped">
      <div class="brand">
        <a href="/">
          <div class="brand__name"><span>#</span>DEVRANT</div>
        </a>
      </div>

      <!-- User Profile -->
      <div class="profile layout--center">
        <div class="profile__picture">
          <svg height="36" width="36">
            <circle cx="18" cy="18" r="18" fill="#5c5f6f"></circle>
          </svg>
        </div>
        <div class="profile__name">Elon</div>
      </div>

      <div class="join">
        <!-- <span>Join</span> -->
        <span (click)="login()">Sign In</span>
        <!-- <span (click)="logout()">Sign Out</span> -->
      </div>
    </div>
  </section>

  <!-- ======================= -->
  <!-- End of Header -->

  <!-- Start of Main Section -->
  <!-- ======================= -->

  <section class="main layout--center">
    <div class="main__content layout--wrapped">
        <router-outlet></router-outlet>
    </div>
  </section>

  <!-- ======================= -->
  <!-- End of Main Section -->

// react/src/components/elements/Header.tsx
import React, { Component, Fragment } from 'react';

export const Header = (props: any) => {
  let header = null;

  header = (
    <section className="header layout--center">
      <div className="header__content layout--wrapped">
        <div className="brand">
          <a href="/">
            <div className="brand__name">
              <span>#</span>DEVRANT
            </div>
          </a>
        </div>

        <div className="profile layout--center">
          <div className="profile__picture">
            <svg height="36" width="36">
              <circle cx="18" cy="18" r="18" fill="#5c5f6f" />
            </svg>
          </div>
          <div className="profile__name">Elon</div>
        </div>

        <div className="join">
          <span>Join</span>
          <span>Sign Out</span>
        </div>
      </div>
    </section>
  );

  return <Fragment>{header}</Fragment>;
};
